export const BODEGA_LANDING_ANIMATION =
  'https://cdn.shopify.com/s/files/1/0759/7506/5791/files/bodega-landing-animation.webp?v=1790288617';

export const BODEGA_BRANDS = [
  {
    key: 'stush',
    number: '01',
    name: 'STUSH',
    tagline: 'Everyday essentials. A higher standard.',
    cta: 'STUSHUSA.COM',
    href: 'https://stushusa.com',
    siteType: 'custom_domain',
    cover: 'https://cdn.shopify.com/s/files/1/0759/7506/5791/files/bodega-stush-card.webp?v=1790286478',
    priority: true,
  },
  {
    key: 'fenyx',
    number: '02',
    name: 'FENYX',
    tagline: 'Built different. Always rising.',
    cta: 'VISIT FENYX SITE',
    href: '/fenyx',
    siteType: 'bodega_alias_to_vercel',
    cover: 'https://cdn.shopify.com/s/files/1/0759/7506/5791/files/bodega-fenyx-card.webp?v=1790286517',
    priority: true,
  },
  {
    key: 'pulse',
    number: '03',
    name: 'PULSE',
    tagline: 'Performance. Clubhouse. Culture.',
    cta: 'YOURPULSEHQ.COM',
    href: 'https://yourpulsehq.com',
    siteType: 'custom_domain',
    cover: 'https://cdn.shopify.com/s/files/1/0759/7506/5791/files/bodega-pulse-card.webp?v=1790286522',
    priority: true,
  },
  {
    key: 'maga',
    number: '04',
    name: 'MAKE ATL GREAT AGAIN',
    tagline: 'People. Culture. Progress.',
    cta: 'THAOLDATLANTA.COM',
    href: '/make-atl-great-again',
    siteType: 'bodega_alias_to_custom_domain',
    cover: 'https://cdn.shopify.com/s/files/1/0759/7506/5791/files/bodega-maga-card.webp?v=1790286526',
  },
  {
    key: 'halloween',
    number: '05',
    name: 'HALLOWEEN CONCERT MERCH',
    tagline: 'Nightmare on Channelside. Tampa.',
    cta: 'SHOP THE FULL MERCH SITE',
    href: '/halloween',
    siteType: 'bodega_alias_to_iconic_merch',
    cover: 'https://cdn.shopify.com/s/files/1/0759/7506/5791/files/bodega-halloween-concert-card.webp?v=1790288611',
  },
  {
    key: 'kollective',
    number: '06',
    name: 'KOLLECTIVE MERCH',
    tagline: 'The uniform for the people building it.',
    cta: 'ENTER KOLLECTIVE',
    href: '/kollective',
    siteType: 'bodega_hosted_full_site',
    cover: 'https://cdn.shopify.com/s/files/1/0759/7506/5791/files/bodega-kollective-card.webp?v=1790286532',
  },
];
